#!/bin/zsh
psql -c "
    UPDATE pg_database
    SET datallowconn = false
    WHERE datname = '$1';
    SELECT pg_terminate_backend(pid)
    FROM pg_stat_activity
    WHERE datname = '$1'
        AND pid <> pg_backend_pid();
" >/dev/null
dropdb $1