#!/usr/bin/env python3

from secrets import token_urlsafe
from hashlib import sha3_512
from sys import argv

if __name__ == '__main__':
    padding = token_urlsafe(32)
    text = argv[1] + ' ' + padding
    hash = sha3_512(text.encode('utf8'))
    print(text)
    print(hash.hexdigest())