tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
brew "ant"
brew "ctags"
brew "gnupg"
brew "duplicity"
brew "duti"
brew "ffmpeg"
brew "fish"
brew "ghostscript"
brew "git"
brew "gitlab-runner"
brew "go"
brew "node"
brew "heroku"
brew "imagemagick"
brew "jq"
brew "kotlin"
brew "leiningen"
brew "mas"
brew "mosh"
brew "multimarkdown"
brew "mysql@5.6", restart_service: true
brew "p7zip"
brew "pandoc"
brew "postgis"
brew "pv"
brew "pwgen"
brew "pyenv"
brew "redis", restart_service: true
brew "ripgrep"
brew "rtmpdump"
brew "ruby", link: true
brew "rustup-init"
brew "sl"
brew "the_silver_searcher"
brew "tree"
brew "watchman"
brew "wget"
cask "1password"
cask "1password-cli"
cask "adobe-creative-cloud"
cask "aerial"
cask "altair-graphql-client"
cask "android-studio"
cask "appcleaner"
cask "arduino"
cask "arq"
cask "atom"
cask "bettertouchtool"
cask "brave-browser"
cask "caffeine"
cask "chocolat"
cask "cyberduck"
cask "daisydisk"
cask "dash"
cask "docker"
cask "firefox"
cask "fliqlo"
cask "font-aleo"
cask "font-fira-code"
cask "font-fira-mono"
cask "font-fira-sans"
cask "font-lato"
cask "font-roboto-mono"
cask "font-source-code-pro"
cask "font-source-sans-pro"
cask "font-source-serif-pro"
cask "font-work-sans"
cask "fontstand"
cask "franz"
cask "gitup"
cask "gog-galaxy"
cask "google-chrome"
cask "google-cloud-sdk"
cask "handbrake"
cask "hex-fiend"
cask "hyper"
cask "iina"
cask "imageoptim"
cask "intellij-idea"
cask "iterm2"
cask "java"
cask "keybase"
cask "kitty"
cask "libreoffice"
cask "mailspring"
cask "makeiphoneringtone"
cask "messenger"
cask "moom"
cask "mplayerx"
cask "netbeans"
cask "ngrok"
cask "notion"
cask "openemu"
cask "opera"
cask "paw"
cask "phoenix"
cask "postbox"
cask "postman"
cask "powershell"
cask "prince"
cask "psequel"
cask "rambox"
cask "rocket"
cask "sauce-connect"
cask "setapp"
cask "sketch"
cask "spotify"
cask "station"
cask "steam"
cask "sublime-text"
cask "teamviewer"
cask "tower"
cask "transmission"
cask "vagrant"
cask "virtualbox"
cask "visual-studio-code"
cask "vivaldi"
cask "vlc"
cask "vmware-fusion"
cask "wickrme"
cask "wkhtmltopdf"
cask "yed"
mas "1Blocker", id: 1107421413
mas "Airmail 3", id: 918858936
mas "Airmail Zero", id: 1460809171
mas "Day One", id: 1055511498
mas "Discovery", id: 1381004916
mas "GhosteryLite", id: 1436953057
mas "Go for Gmail", id: 979538493
mas "Kiwi for Gmail", id: 986304488
mas "LINE", id: 539883307
mas "Numbers", id: 409203825
mas "One Chat Lite", id: 1239183246
mas "Pages", id: 409201541
mas "Slack", id: 803453959
mas "Tweetbot", id: 1384080005
mas "Twitterrific", id: 1289378661
mas "Wire", id: 931134707
