[symlinks]
vscode-config = "~/Library/Application Support/Code/User"
fish-config = "~/.config/fish"
git-config = "~/.gitconfig"
git-ignore = "~/.git-ignore-global"
git-template = "~/.git-template"
git-message = "~/.git-message"

[homebrew]
taps = [
    "homebrew/bundle",
    "homebrew/cask",
    "homebrew/cask-fonts",
    "homebrew/core",
    "homebrew/services",
]
brews = [
    "docker",
    "duti",
    "ffmpeg",
    "fish",
    "git",
    "gitlab-runner",
    "heroku",
    "jq",
    "mas",
    "mosh",
    "node",
    "p7zip",
    "pandoc",
    "pv",
    "pyenv",
    "ripgrep",
    "rtmpdump",
    "rustup-init",
    "tree",
    "watchman",
    "wget",
]
casks = [
    "1password-cli",
    "1password",
    "adobe-creative-cloud",
    "android-studio",
    "appcleaner",
    "bettertouchtool",
    "dash",
    "docker",
    "firefox",
    "fliqlo",
    "font-aleo",
    "font-fira-code",
    "font-fira-mono",
    "font-fira-sans",
    "font-lato",
    "font-roboto-mono",
    "font-source-code-pro",
    "font-source-sans-pro",
    "font-source-serif-pro",
    "font-work-sans",
    "fontstand",
    "gitup",
    "google-cloud-sdk",
    "handbrake",
    "hex-fiend",
    "iina",
    "imageoptim",
    "iterm2",
    "java",
    "messenger",
    "moom",
    "ngrok",
    "notion",
    "openemu",
    "opera",
    "paw",
    "phoenix",
    "postman",
    "rocket",
    "setapp",
    "sketch",
    "spotify",
    "teamviewer",
    "transmission",
    "visual-studio-code",
    "vlc",
    "wkhtmltopdf",
]

[python]
global-version = '3.7.1'
tools = [
    'black',
    'boom',
    'cookiecutter',
    'httpie',
    'mycli',
    'nox',
    # 'pgcli',
    'pre-commit',
    'tox',
    'twine',
]

[vscode]
extensions = [
    "onecrayon.theme-quietlight-vsc",
    "ms-vscode-remote.remote-wsl",
    "thenikso.github-plus-theme",
    "akamud.vscode-theme-onelight",
    "ms-python.python",
    "lextudio.restructuredtext",
    "ms-vscode-remote.remote-containers",
    "ms-vscode-remote.vscode-remote-extensionpack",
    "bungcip.better-toml",
    "TabNine.tabnine-vscode",
    "EditorConfig.EditorConfig",
    "esbenp.prettier-vscode",
    "lunaryorn.fish-ide",
    "kalitaalexey.vscode-rust",
    "kumar-harsh.graphql-for-vscode",
    "ms-vscode-remote.remote-ssh-edit",
    "streetsidesoftware.code-spell-checker",
    "rust-lang.rust",
    "formulahendry.auto-rename-tag",
    "ms-vscode-remote.remote-ssh",
    "ms-vscode-remote.remote-ssh-explorer",
    "redhat.java",
    "skyapps.fish-vscode",
    "ms-azuretools.vscode-docker",
]