[symlinks]
vscode = "~/Library/Application Support/Code/User"
fish = "~/.config/fish"
"git/config" = "~/.gitconfig"
"xonsh/rc.xsh" = "~/.xonshrc"
"asdf/global-versions" = "~/.tool-versions"

[homebrew.taps]
"homebrew/bundle" = true
"homebrew/cask-drivers" = true
"homebrew/cask-fonts" = true
"homebrew/cask" = true
"homebrew/core" = true
"homebrew/services" = true
"teamookla/speedtest" = true
"adoptopenjdk/openjdk" = true
"cuelang/tap" = true
"filippo.io/age" = "\"https://filippo.io/age\""
"filippo.io/yubikey-agent" = "\"https://filippo.io/yubikey-agent\""
"getsentry/tools" = true
"github/gh" = true
"microsoft/git" = true

[homebrew.brews]
"cuelang/tap/cue" = true
"getsentry/tools/sentry-cli" = true
"github/gh/gh" = true
"teamookla/speedtest/speedtest" = true
# ffmpeg = true # fails to install for some reason
# gradle = true
# heroku = true
# node = true - installed via 'n'
age = true
asdf = true
bundletool = true
cocoapods = true
cpulimit = true
devd = true
direnv = true
doctl = true
duti = true
ffmpeg = true
fish = true
gdb = true
git = true
gitlab-runner = true
gnupg = true
htop = true
jq = true
ktlint = true
kubernetes-cli = true
lastpass-cli = true
lego = true
libffi = true
libgit2 = true
libmagic = true
libpq = true # needed for pgcli
libressl = true
llvm = true
mas = true
micropython = true
modd = true
mosh = true
mysql-client = true
openssh = true
p7zip = true
pandoc = true
pipx = true
pstree = true
pv = true
restic = true
ripgrep = true
rsync = true
rtmpdump = true
rustup-init = true
socat = true
sqlcipher = true
sshuttle = true
tree = true
watchman = true
wget = true
ykman = true
yubikey-agent = "restart_service: true"
"openssl@1.1" = true
readline = true
caddy = true
xz = true
cairo = true
cmake = true
fcct = true
gdk-pixbuf = true
git-delta = true
harfbuzz = true
libzt = true
mp3gain = true
pango = true
sox = true
tldr = true

[homebrew.casks]
# virtualbox = true
1password = true
1password-cli = true
adoptopenjdk8 = true
alfred = true
android-studio = true
appcleaner = true
balenaetcher = true
bettertouchtool = true
chatmate-for-whatsapp = true
chrysalis = true
daisydisk = true
dash = true
discord = true
docker = true
dolphin = true
dotnet-sdk = true
enjoyable = true
fanny = true
figma = true
firefox = true
fliqlo = true
font-fira-code = true
font-fira-mono = true
font-fira-sans = true
font-input = true
font-inter = true
font-lato = true
font-overpass = true
font-pt-sans = true
font-source-code-pro = true
font-source-sans-pro = true
font-source-serif-pro = true
font-work-sans = true
fontstand = true
framer-x = true
gitup = true
google-chrome = true
google-cloud-sdk = true
graphiql = true
hammerspoon = true
handbrake = true
hex-fiend = true
iina = true
imageoptim = true
itch = true
iterm2 = true
kensington-trackball-works = true
lastpass = true
moom = true
mountain-duck = true
netnewswire = true
ngrok = true
notion = true
obs = true
openemu = true
osxfuse = true
parallels = true
patchwork = true
paw = true
phoenix = true
plex = true
plex-media-player = true
postman = true
quitter = true
retroarch = true
rocket = true
setapp = true
signal = true
sixtyforce = true
sketch = true
sketchup = true
slack = true
spotify = true
steam = true
tableplus = true
teamviewer = true
textmate = true
transmission = true
vagrant = true
videostream = true
visual-studio-code = true
# vlc = true
volt = true
webex-teams = true
wireshark = true
wkhtmltopdf = true
workflowy = true
xscreensaver = true
yubico-authenticator = true
yubico-yubikey-manager = true
zerotier-one = true
zoomus = true
git-credential-manager-core = true
mailspring = true
parsec = true
sekey = true
yt-music = true

[python]
global-version = "3.8.0"
extra-path = ["/usr/local/opt/libpq/bin"]
library-path = ["/usr/local/opt/openssl/lib"]
tools = [
    "awscli",
    "bandit",
    "black",
    "boom",
    "cookiecutter",
    "flake8",
    "httpie",
    "litecli",
    "mycli",
    "nox",
    "pgcli",
    "pre-commit",
    "rshell",
    "tox",
    "twine",
]

[vscode]
extensions = [
    "akamud.vscode-theme-onelight",
    "apollographql.vscode-apollo",
    "bungcip.better-toml",
    "champgm.cloudformation-yaml-validator",
    "eamodio.gitlens",
    "EditorConfig.EditorConfig",
    "esbenp.prettier-vscode",
    "formulahendry.auto-rename-tag",
    "fwcd.kotlin",
    "kumar-harsh.graphql-for-vscode",
    "lextudio.restructuredtext",
    "lunaryorn.fish-ide",
    "ms-azuretools.vscode-docker",
    "ms-python.python",
    "ms-vscode-remote.remote-containers",
    "ms-vscode-remote.remote-ssh-edit",
    "ms-vscode-remote.remote-ssh-explorer",
    "ms-vscode-remote.remote-ssh",
    "ms-vscode-remote.remote-wsl",
    "ms-vscode-remote.vscode-remote-extensionpack",
    "onecrayon.theme-quietlight-vsc",
    "redhat.java",
    "rust-lang.rust",
    "skyapps.fish-vscode",
    "streetsidesoftware.code-spell-checker",
    "TabNine.tabnine-vscode",
    "thenikso.github-plus-theme",
    "tomoki1207.pdf",
    "VisualStudioExptTeam.vscodeintellicode",
    "vscjava.vscode-java-debug",
    "vscjava.vscode-java-dependency",
    "vscjava.vscode-java-pack",
    "vscjava.vscode-java-test",
    "vscjava.vscode-maven",
    "wix.vscode-import-cost",
    "iansan5653.format-python-docstrings",
, "kalitaalexey.vscode-rust", "adpyke.vscode-sql-formatter", "kddejong.vscode-cfn-lint", "samuelcolvin.jinjahtml", "zhouronghui.propertylist", "hangxingliu.vscode-systemd-support", "tkw01536.git-commit-format", "keyboardDrummer.vscode-cloudformation", "svelte.svelte-vscode", "liviuschera.noctis", "redhat.vscode-yaml", "ms-kubernetes-tools.vscode-kubernetes-tools", "zamerick.vscode-caddyfile-syntax", "ms-python.vscode-pylance", "alefragnani.Bookmarks"]

[rust]