[symlinks]
vscode-config = "~/Library/Application Support/Code/User"
fish-config = "~/.config/fish"
git-config = "~/.gitconfig"
git-ignore = "~/.git-ignore-global"
git-template = "~/.git-template"
git-message = "~/.git-message"

[homebrew]
taps = [
    "homebrew/bundle",
    "homebrew/cask",
    "homebrew/cask-fonts",
    "homebrew/core",
    "homebrew/services",
]
brews = [
    "duti",
    "ffmpeg",
    "fish",
    "git",
    "gitlab-runner",
    "go",
    "heroku",
    "imagemagick",
    "jq",
    "mas",
    "mosh",
    "node",
    "p7zip",
    "pandoc",
    "pv",
    "pyenv",
    "ripgrep",
    "rtmpdump",
    "rustup-init",
    "sl",
    "tree",
    "watchman",
    "wget",
]
casks = [
    "1password-cli",
    "1password",
    "adobe-creative-cloud",
    "android-studio",
    "appcleaner",
    "bettertouchtool",
    "daisydisk",
    "dash",
    "docker",
    "firefox",
    "fliqlo",
    "font-aleo",
    "font-fira-code",
    "font-fira-mono",
    "font-fira-sans",
    "font-lato",
    "font-roboto-mono",
    "font-source-code-pro",
    "font-source-sans-pro",
    "font-source-serif-pro",
    "font-work-sans",
    "fontstand",
    "gitup",
    "gog-galaxy",
    "google-chrome",
    "google-cloud-sdk",
    "handbrake",
    "hex-fiend",
    "hyper",
    "iina",
    "imageoptim",
    "intellij-idea",
    "iterm2",
    "java",
    "keybase",
    "kitty",
    "libreoffice",
    "mailspring",
    "makeiphoneringtone",
    "messenger",
    "moom",
    "mplayerx",
    "netbeans",
    "ngrok",
    "notion",
    "openemu",
    "opera",
    "paw",
    "phoenix",
    "postman",
    "powershell",
    "prince",
    "psequel",
    "rocket",
    "setapp",
    "sketch",
    "spotify",
    "station",
    "steam",
    "sublime-text",
    "teamviewer",
    "tower",
    "transmission",
    "vagrant",
    "virtualbox",
    "visual-studio-code",
    "vivaldi",
    "vlc",
    "vmware-fusion",
    "wkhtmltopdf",
]

[vscode]
extensions = [
    "onecrayon.theme-quietlight-vsc",
    "ms-vscode-remote.remote-wsl",
    "thenikso.github-plus-theme",
    "akamud.vscode-theme-onelight",
    "ms-python.python",
    "lextudio.restructuredtext",
    "ms-vscode-remote.remote-containers",
    "ms-vscode-remote.vscode-remote-extensionpack",
    "bungcip.better-toml",
    "TabNine.tabnine-vscode",
    "EditorConfig.EditorConfig",
    "esbenp.prettier-vscode",
    "lunaryorn.fish-ide",
    "kalitaalexey.vscode-rust",
    "kumar-harsh.graphql-for-vscode",
    "ms-vscode-remote.remote-ssh-edit",
    "streetsidesoftware.code-spell-checker",
    "rust-lang.rust",
    "formulahendry.auto-rename-tag",
    "ms-vscode-remote.remote-ssh",
    "ms-vscode-remote.remote-ssh-explorer",
    "redhat.java",
    "skyapps.fish-vscode",
    "ms-azuretools.vscode-docker",
]