[symlinks]
vscode = "~/Library/Application Support/Code/User"
fish = "~/.config/fish"
"git/config" = "~/.gitconfig"
"xonsh/rc.xsh" = "~/.xonshrc"
"asdf/global-versions" = "~/.tool-versions"
"Yarn Global" = "~/.config/yarn/global"
"Nova" = "~/Library/Application Support/Nova"
"Hammerspoon" = "~/.hammerspoon"
"Zsh/rc.sh" = "~/.zshrc"
"Zsh/env.sh" = "~/.zshenv"
"xonsh/_sitecustomize.py" = "~/.local/pipx/venvs/xonsh/lib/python3.9/site-packages/sitecustomize.py"

[homebrew.taps]
"homebrew/bundle" = true
"homebrew/cask-drivers" = true
"homebrew/cask-fonts" = true
"homebrew/cask" = true
"homebrew/core" = true
"homebrew/services" = true
"teamookla/speedtest" = true
"adoptopenjdk/openjdk" = true
"filippo.io/age" = "\"https://filippo.io/age\""
"filippo.io/yubikey-agent" = "\"https://filippo.io/yubikey-agent\""
"getsentry/tools" = true
"microsoft/git" = true
"heroku/brew" = true
"cuelang/tap" = true
"github/gh" = true
"homebrew/cask-versions" = true
"cue-lang/tap" = true
"hivemq/mqtt-cli" = true
"romkatv/gitstatus" = true
"superfly/tap" = true

[homebrew.brews]
"getsentry/tools/sentry-cli" = true
"teamookla/speedtest/speedtest" = true
# ffmpeg = true # fails to install for some reason
# gradle = true
# heroku = true
# node = true - installed via 'n'
age = true
asdf = true
bundletool = true
cocoapods = true
cpulimit = true
devd = true
direnv = true
doctl = true
duti = true
ffmpeg = true
gdb = true
git = true
gnupg = true
htop = true
jq = true
ktlint = true
kubernetes-cli = true
lego = true
libffi = true
libgit2 = true
libmagic = true
libpq = true # needed for pgcli
libressl = true
llvm = true
mas = true
micropython = true
modd = true
mosh = true
openssh = true
p7zip = true
pandoc = true
pstree = true
pv = true
restic = true
ripgrep = true
rsync = true
rtmpdump = true
rustup-init = true
socat = true
sqlcipher = true
sshuttle = true
tree = true
watchman = true
wget = true
ykman = true
yubikey-agent = "restart_service: true"
"openssl@1.1" = true
readline = true
caddy = true
xz = true
cairo = true
cmake = true
fcct = true
gdk-pixbuf = true
git-delta = true
harfbuzz = true
libzt = true
mp3gain = true
pango = true
sox = true
tldr = true
automake = true
azcopy = true
glib = true
pkg-config = true
gnutls = true
gobject-introspection = true
freetds = true
libfido2 = true
libmemcached = true
libsixel = true
memcached = true
minicom = true
namebench = true
putty = true
rabbitmq = "restart_service: true"
sloccount = true
yubico-piv-tool = true
"heroku/brew/heroku" = true
"cuelang/tap/cue" = true
jpeg = true
erlang = true
giflib = true
gh = true
gitlab-runner = true
krb5 = true
sphinx-doc = true
libtool = true
blueutil = true
butane = true
bzip2 = true
"python@3.10" = true
ccls = true
ctags = true
dnscontrol = true
guile = true
libass = true
srt = true
node = true
firebase-cli = true
folly = true
fzf = true
git-absorb = true
tcl-tk = true
libheif = true
imagemagick = true
ldns = true
libssh = true
libusb-compat = true
libvirt = true
libwebsockets = true
ninja = true
meson = true
mosquitto = true
neovim = true
netlify-cli = true
nghttp2 = true
pacparser = true
picocom = true
platformio = true
qemu = true
podman = true
qt = true
poppler = true
"python@3.8" = true
rabbitmq-c = true
rust-analyzer = true
shadowsocks-libev = "restart_service: true"
swig = true
transmission-cli = true
wtf = true
zlib = true
"cue-lang/tap/cue" = true
"hivemq/mqtt-cli/mqtt-cli" = true
"romkatv/gitstatus/gitstatus" = true
"superfly/tap/flyctl" = true

[homebrew.casks]
# virtualbox = true
# 1password = true
1password-cli = true
# alfred = true
# android-studio = true
appcleaner = true
balenaetcher = true
# bettertouchtool = true
chatmate-for-whatsapp = true
chrysalis = true
daisydisk = true
dash = true
discord = true
docker = true
# dolphin = true
# dotnet-sdk = true
enjoyable = true
fanny = true
figma = true
firefox = true
fliqlo = true
font-fira-code = true
font-fira-mono = true
font-fira-sans = true
font-input = true
font-inter = true
font-lato = true
font-overpass = true
font-pt-sans = true
#font-source-code-pro = true
#font-source-sans-pro = true
#font-source-serif-pro = true
font-work-sans = true
fontstand = true
framer-x = true
gitup = true
google-cloud-sdk = true
graphiql = true
hammerspoon = true
handbrake = true
hex-fiend = true
iina = true
imageoptim = true
itch = true
iterm2 = true
# kensington-trackball-works = true
# moom = true
mountain-duck = true
# netnewswire = true
ngrok = true
notion = true
obs = true
# openemu = true
osxfuse = true
# parallels = true
patchwork = true
paw = true
phoenix = true
plex-media-player = true
postman = true
# quitter = true
# retroarch = true
# rocket = true
setapp = true
# signal = true
# sixtyforce = true
sketch = true
# sketchup = true
# slack = true # installed through MAS
# spotify = true
# steam = true
tableplus = true
textmate = true
# transmission = true
vagrant = true
# videostream = true
# visual-studio-code = true
# vlc = true
volt = true
wireshark = true
# wkhtmltopdf = true
# workflowy = true
# xscreensaver = true
yubico-authenticator = true
yubico-yubikey-manager = true
zerotier-one = true
zoomus = true
git-credential-manager-core = true
# mailspring = true
parsec = true
sekey = true
yt-music = true
aegisub = true
arduino = true
audio-hijack = true
choosy = true
focused = true
ftdi-vcp-driver = true
kaleidoscope = true
mattermost = true
# pycharm = true
silicon-labs-vcp-driver = true
chromium = true
geektool = true
inkscape = true
istat-menus = true
launchcontrol = true
multi = true
typora = true
vivaldi = true
nova = true
zoom = true
8bitdo-ultimate-software = true
adobe-acrobat-reader = true
airserver = true
alfred = true
asana = true
atext = true
audacity = true
autodesk-fusion360 = true
canon-eos-utility = true
canon-eos-webcam-utility = true
crossover = true
dolphin = true
dropbox = true
duet = true
dymo-label = true
element = true
font-catamaran = true
font-public-sans = true
font-sf-compact = true
font-sf-mono = true
font-sf-pro = true
font-source-code-pro = true
font-source-sans-pro = true
font-source-serif-pro = true
gather = true
google-chrome = true
krisp = true
launchbar = true
logitech-camera-settings = true
loopback = true
microsoft-auto-update = true
microsoft-edge = true
monodraw = true
mullvadvpn = true
netdownloadhelpercoapp = true
openscad = true
paragon-extfs = true
raspberry-pi-imager = true
sidequest = true
signal = true
steam = true
sublime-merge = true
sublime-text = true
the-unarchiver = true
transmission = true
ubar = true
vimr = true
virtualbox = true
virtualbox-extension-pack = true
visual-studio-code = true
vlc = true
wire = true

[python]
global-version = "3.8.0"
extra-path = ["/usr/local/opt/libpq/bin"]
library-path = ["/usr/local/opt/openssl/lib"]
tools = [
  "awscli",
  "bandit",
  "black",
  "boom",
  "cookiecutter",
  "flake8",
  "httpie",
  "litecli",
  "mycli",
  "nox",
  "pgcli",
  "pre-commit",
  "rshell",
  "tox",
  "twine",
  "youtube-dl",
  "xonsh",
  "adafruit-ampy",
  "pipenv",
  "esptool",
  "mypy",
]

[vscode]
extensions = [
  "akamud.vscode-theme-onelight",
  "apollographql.vscode-apollo",
  "bungcip.better-toml",
  "champgm.cloudformation-yaml-validator",
  "eamodio.gitlens",
  "EditorConfig.EditorConfig",
  "esbenp.prettier-vscode",
  "formulahendry.auto-rename-tag",
  "fwcd.kotlin",
  "kumar-harsh.graphql-for-vscode",
  "lextudio.restructuredtext",
  "lunaryorn.fish-ide",
  "ms-azuretools.vscode-docker",
  "ms-python.python",
  "ms-vscode-remote.remote-containers",
  "ms-vscode-remote.remote-ssh-edit",
  "ms-vscode-remote.remote-ssh-explorer",
  "ms-vscode-remote.remote-ssh",
  "ms-vscode-remote.remote-wsl",
  "ms-vscode-remote.vscode-remote-extensionpack",
  "onecrayon.theme-quietlight-vsc",
  "redhat.java",
  "rust-lang.rust",
  "skyapps.fish-vscode",
  "streetsidesoftware.code-spell-checker",
  "TabNine.tabnine-vscode",
  "thenikso.github-plus-theme",
  "tomoki1207.pdf",
  "VisualStudioExptTeam.vscodeintellicode",
  "vscjava.vscode-java-debug",
  "vscjava.vscode-java-dependency",
  "vscjava.vscode-java-pack",
  "vscjava.vscode-java-test",
  "vscjava.vscode-maven",
  "wix.vscode-import-cost",
  "iansan5653.format-python-docstrings",
  "adpyke.vscode-sql-formatter",
  "kddejong.vscode-cfn-lint",
  "samuelcolvin.jinjahtml",
  "zhouronghui.propertylist",
  "hangxingliu.vscode-systemd-support",
  "tkw01536.git-commit-format",
  "keyboardDrummer.vscode-cloudformation",
  "svelte.svelte-vscode",
  "liviuschera.noctis",
  "redhat.vscode-yaml",
  "ms-kubernetes-tools.vscode-kubernetes-tools",
  "zamerick.vscode-caddyfile-syntax",
  "ms-python.vscode-pylance",
  "alefragnani.Bookmarks",
  "ms-pyright.pyright",
  "ms-toolsai.jupyter"
]

[rust]
