[symlinks]
vscode-config = "~/Library/Application Support/Code/User"
fish-config = "~/.config/fish"
git-config = "~/.gitconfig"
git-ignore = "~/.git-ignore-global"
git-template = "~/.git-template"
git-message = "~/.git-message"
"xonsh/rc.xsh" = "~/.xonshrc"

[homebrew.taps]
"homebrew/bundle" = true
"homebrew/cask-drivers" = true
"homebrew/cask-fonts" = true
"homebrew/cask" = true
"homebrew/core" = true
"homebrew/services" = true
"teamookla/speedtest" = true
"adoptopenjdk/openjdk" = true

[homebrew.brews]
"mysql@5.6" = true
"mysql@5.7" = true
"postgresql@9.6" = true
"teamookla/speedtest/speedtest" = true
# ffmpeg = true # fails to install for some reason
# heroku = true
# node = true - installed via 'n'
cocoapods = true
cpulimit = true
devd = true
duti = true
fish = true
gdb = true
git = true
gitlab-runner = true
# gradle = true
htop = true
jq = true
ktlint = true
libgit2 = true
libpq = {link = "true"} # needed for pgcli
mas = true
micropython = true
modd = true
mosh = true
mysql-client = true
n = true
p7zip = true
pandoc = true
pv = true
pyenv = true
restic = true
ripgrep = true
rsync = true
rtmpdump = true
rustup-init = true
socat = true
tree = true
watchman = true
wget = true

[homebrew.casks]
1password = true
1password-cli = true
adobe-creative-cloud = true
alfred = true
android-studio = true
appcleaner = true
balenaetcher = true
bettertouchtool = true
chatmate-for-whatsapp = true
daisydisk = true
dash = true
discord = true
docker = true
figma = true
firefox = true
fliqlo = true
font-fira-code = true
font-fira-mono = true
font-fira-sans = true
font-inter = true
font-lato = true
font-overpass = true
font-pt-sans = true
font-roboto-mono = true
font-source-code-pro = true
font-source-sans-pro = true
font-source-serif-pro = true
font-work-sans = true
fontstand = true
gitup = true
google-chrome = true
google-cloud-sdk = true
handbrake = true
hex-fiend = true
iina = true
imageoptim = true
iterm2 = true
lastpass = true
moom = true
mountain-duck = true
ngrok = true
notion = true
openemu = true
opera = true
parallels = true
paw = true
phoenix = true
plex-media-player = true
postman = true
rocket = true
setapp = true
sketch = true
slack = true
spotify = true
teamviewer = true
textmate = true
transmission = true
videostream = true
# virtualbox = true
visual-studio-code = true
vlc = true
volt = true
wkhtmltopdf = true
workflowy = true
yubico-authenticator = true
zerotier-one = true
adoptopenjdk8 = true

[python]
global-version = "3.8.0"
extra-path = ["/usr/local/opt/libpq/bin"]
library-path = ["/usr/local/opt/openssl/lib"]
tools = [
    "awscli",
    "bandit",
    "black",
    "boom",
    "cookiecutter",
    "flake8",
    "httpie",
    "litecli",
    "mycli",
    "nox",
    "pgcli",
    "pre-commit",
    "rshell",
    "tox",
    "twine",
]

[python.pyenv-plugins]
pyenv-virtualenv = "https://github.com/pyenv/pyenv-virtualenv.git"
xxenv-latest = "https://github.com/momo-lab/xxenv-latest.git"

[vscode]
extensions = [
    "akamud.vscode-theme-onelight",
    "apollographql.vscode-apollo",
    "bungcip.better-toml",
    "champgm.cloudformation-yaml-validator",
    "eamodio.gitlens",
    "EditorConfig.EditorConfig",
    "esbenp.prettier-vscode",
    "formulahendry.auto-rename-tag",
    "fwcd.kotlin",
    "kalitaalexey.vscode-rust",
    "kumar-harsh.graphql-for-vscode",
    "lextudio.restructuredtext",
    "lunaryorn.fish-ide",
    "ms-azuretools.vscode-docker",
    "ms-python.python",
    "ms-vscode-remote.remote-containers",
    "ms-vscode-remote.remote-ssh-edit",
    "ms-vscode-remote.remote-ssh-explorer",
    "ms-vscode-remote.remote-ssh",
    "ms-vscode-remote.remote-wsl",
    "ms-vscode-remote.vscode-remote-extensionpack",
    "onecrayon.theme-quietlight-vsc",
    "redhat.java",
    "rust-lang.rust",
    "skyapps.fish-vscode",
    "streetsidesoftware.code-spell-checker",
    "TabNine.tabnine-vscode",
    "thenikso.github-plus-theme",
    "tomoki1207.pdf",
    "VisualStudioExptTeam.vscodeintellicode",
    "vscjava.vscode-java-debug",
    "vscjava.vscode-java-dependency",
    "vscjava.vscode-java-pack",
    "vscjava.vscode-java-test",
    "vscjava.vscode-maven",
    "wix.vscode-import-cost",
    "iansan5653.format-python-docstrings",
]

[rust]