[symlinks]
vscode = "~/Library/Application Support/Code/User"
fish = "~/.config/fish"
"git/config" = "~/.gitconfig"
"xonsh/rc.xsh" = "~/.xonshrc"
"asdf/global-versions" = "~/.tool-versions"
"Yarn Global" = "~/.config/yarn/global"
#"Nova" = "~/Library/Application Support/Nova"
"Hammerspoon" = "~/.hammerspoon"
"Zsh/rc.sh" = "~/.zshrc"
"Zsh/env.sh" = "~/.zshenv"
"xonsh/_sitecustomize.py" = "~/.local/pipx/venvs/xonsh/lib/python3.9/site-packages/sitecustomize.py"
"~/Library/Mobile Documents/com~apple~CloudDocs/Spelling" = "~/Library/Spelling"

[python]
extra-path = ["/opt/homebrew/opt/libpq/bin"]
library-path = ["/opt/homebrew/opt/openssl/lib"]
tools = [
  "awscli",
  "bandit",
  "black",
  "boom",
  "cookiecutter",
  "flake8",
  "httpie",
  "litecli",
  "mycli",
  "nox",
  "pgcli",
  "pre-commit",
  "rshell",
  "tox",
  "twine",
  "youtube-dl",
  "xonsh",
  "adafruit-ampy",
  "pipenv",
  "esptool",
  "mypy",
]

[vscode]
extensions = [
  "akamud.vscode-theme-onelight",
  "apollographql.vscode-apollo",
  "bungcip.better-toml",
  "champgm.cloudformation-yaml-validator",
  "eamodio.gitlens",
  "EditorConfig.EditorConfig",
  "esbenp.prettier-vscode",
  "formulahendry.auto-rename-tag",
  "fwcd.kotlin",
  "kumar-harsh.graphql-for-vscode",
  "lextudio.restructuredtext",
  "lunaryorn.fish-ide",
  "ms-azuretools.vscode-docker",
  "ms-python.python",
  "ms-vscode-remote.remote-containers",
  "ms-vscode-remote.remote-ssh-edit",
  "ms-vscode-remote.remote-ssh-explorer",
  "ms-vscode-remote.remote-ssh",
  "ms-vscode-remote.remote-wsl",
  "ms-vscode-remote.vscode-remote-extensionpack",
  "onecrayon.theme-quietlight-vsc",
  "redhat.java",
  "rust-lang.rust",
  "skyapps.fish-vscode",
  "streetsidesoftware.code-spell-checker",
  "TabNine.tabnine-vscode",
  "thenikso.github-plus-theme",
  "tomoki1207.pdf",
  "VisualStudioExptTeam.vscodeintellicode",
  "vscjava.vscode-java-debug",
  "vscjava.vscode-java-dependency",
  "vscjava.vscode-java-pack",
  "vscjava.vscode-java-test",
  "vscjava.vscode-maven",
  "wix.vscode-import-cost",
  "iansan5653.format-python-docstrings",
  "adpyke.vscode-sql-formatter",
  "kddejong.vscode-cfn-lint",
  "samuelcolvin.jinjahtml",
  "zhouronghui.propertylist",
  "hangxingliu.vscode-systemd-support",
  "tkw01536.git-commit-format",
  "keyboardDrummer.vscode-cloudformation",
  "svelte.svelte-vscode",
  "liviuschera.noctis",
  "redhat.vscode-yaml",
  "ms-kubernetes-tools.vscode-kubernetes-tools",
  "zamerick.vscode-caddyfile-syntax",
  "ms-python.vscode-pylance",
  "alefragnani.Bookmarks",
  "ms-pyright.pyright",
  "ms-toolsai.jupyter"
]

[rust]
