#!/usr/bin/env zsh
for receipt in $(find /opt/homebrew/Cellar/$1/*/INSTALL_RECEIPT.json); do
    cat <<< $(jq '.installed_on_request = false | .installed_as_dependency = true' $receipt) > $receipt
done
