#!/usr/bin/env python3

from sys import argv
from pathlib import Path
from subprocess import check_call

target_dir = Path(argv[1] if len(argv) > 1 else '.').resolve()
workspace_file = target_dir.parent / (target_dir.name + '.code-workspace')
if workspace_file.exists():
    check_call(('code', workspace_file))
else:
    check_call(('code', target_dir))
