#!/usr/bin/env python

# /etc/periodic.conf
# $daily_clean_tmps_ignore = "$daily_clean_tmps_ignore *.link-target"

from urllib.parse import quote_plus
from pathlib import Path
from hashlib import sha224
from base64 import urlsafe_b64encode
from os.path import abspath
import sys


tmpdir = Path('~/Library/Caches/Links').expanduser()
source = Path(sys.argv[1])

hash = sha224(abspath(source).encode('utf8'))
digest = urlsafe_b64encode(hash.digest()).decode('utf8').rstrip('=')
filename = f'{source.name}.{digest}'

target = tmpdir / filename
target.mkdir(exist_ok=True, parents=True)
if source.is_symlink():
    source.unlink()
source.symlink_to(target)