#!/bin/zsh

SCRIPT="from django.contrib.auth import get_user_model

User = get_user_model()
for n in ('leigh', 'lbrenecki', 'adam', 'abrenecki'):
	try:
		u = User.objects.get(username=n)
	except User.DoesNotExist:
		continue
	else:
		break
else:
	u = User.objects.filter(is_superuser=True).first()
u.set_password('password')
u.is_active = True
u.save()
print('{0.username} / password'.format(u))"

MANAGEPY=$(find . -name "manage.py" | head -n1)

if test -v 1; then
	echo $SCRIPT | $* shell
elif test -f poetry.lock; then
	echo $SCRIPT | poetry run python $MANAGEPY shell
elif test -f Pipfile; then
    echo $SCRIPT | pipenv run python $MANAGEPY shell
else
    echo $SCRIPT | python $MANAGEPY shell
fi
