#!/usr/bin/env python

import pathlib
import sys
import os
from textwrap import dedent

requested_dir_or_file = pathlib.Path(sys.argv[1]) if len(sys.argv) == 2 else pathlib.Path.cwd()

if requested_dir_or_file.is_dir():
    project_file = requested_dir_or_file.parent / f"{requested_dir_or_file.name}.sublime-project"
    if not project_file.exists():
        with project_file.open('w') as f:
            f.write(dedent(f"""
                {{
                    "folders":
                    [
                        {{
                            "path": "{requested_dir_or_file.name}"
                        }}
                    ]
                }}
                """))
    os.execlp("subl", "subl", str(project_file))
else:
    os.execlp("subl", "subl", str(requested_dir_or_file))