#!/usr/bin/env zsh
set -euo pipefail

PR_NUMBER=$1
# TODO: use graphql to avoid roundtrips
HEAD_SHA=$(gh api "/repos/{owner}/{repo}/pulls/$PR_NUMBER" -q '.head.sha')
LAST_REVIEW_SHA=$(gh api "/repos/{owner}/{repo}/pulls/$PR_NUMBER/reviews" -q 'map(select(.user.id == 473960) | .commit_id)[-1]')
if test $(git cat-file -t $LAST_REVIEW_SHA || echo 'none') != commit -o $(git cat-file -t $HEAD_SHA || echo 'none') != commit; then
    git fetch origin $LAST_REVIEW_SHA $HEAD_SHA
fi
git range-diff main $LAST_REVIEW_SHA $HEAD_SHA