#!/usr/bin/env python

import sys
import subprocess

for line in sys.stdin:
    if (sha := line.removeprefix('missing blob ')) != line:
        sha = sha.strip()
        print(f"{sha=}")
        commit_sha = subprocess.run(('git', 'log', '--format=%H', '--all', f'--find-object={sha}'), stdout=subprocess.PIPE).stdout.strip()
        print(f"{commit_sha=}")