#!/usr/bin/env python
import sys
from pathlib import Path
import os

cwd = Path.cwd()

if cwd.is_relative_to(Path('~/Octopus/kraken-core').expanduser()):
	os.execvp('process-compose', ['process-compose', 'up', *sys.argv[1:]])