#!/usr/bin/env python3

from secrets import token_urlsafe
from hashlib import sha3_256
from sys import argv
from base64 import urlsafe_b64encode, b32encode

if __name__ == '__main__':
    padding = token_urlsafe(32)
    text = argv[1] + ' ' + padding
    hash = sha3_256(text.encode('utf8'))
    print('orig text:  ', text)
    print('b64 digest: ', urlsafe_b64encode(hash.digest()).decode('utf8'))
    print('hex digest: ', hash.hexdigest())