#!/usr/bin/env python3
import tempfile
import sys
import subprocess
import pathlib

with tempfile.NamedTemporaryFile('w', delete=False) as playlist:
    for filename in sys.argv[1:]:
        fp = pathlib.Path(filename)
        playlist.write(f"file {fp.absolute()}\n")
    playlist.flush()
    subprocess.run(('ffmpeg', '-f', 'concat', '-safe', '0', '-i', playlist.name, '-c', 'copy', 'output.mp4'))